const ERROR_CODES = {
  AUTH: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    TOKEN_MISSING: 'TOKEN_MISSING',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
    ACCOUNT_ALREADY_EXISTS: 'ACCOUNT_ALREADY_EXISTS',
    REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  },
  USER: {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  },
  PRODUCT: {
    PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
    PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
    DUPLICATE_PRODUCT_SLUG: 'DUPLICATE_PRODUCT_SLUG',
  },
  ORDER: {
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDER_CANNOT_BE_CANCELLED: 'ORDER_CANNOT_BE_CANCELLED',
    INVALID_ORDER_STATUS_TRANSITION: 'INVALID_ORDER_STATUS_TRANSITION',
  },
  CART: {
    CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  },
  PAYMENT: {
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    STRIPE_WEBHOOK_INVALID: 'STRIPE_WEBHOOK_INVALID',
    PAYMENT_INTENT_FAILED: 'PAYMENT_INTENT_FAILED',
  },
  MEDIA: {
    IMAGE_UPLOAD_FAILED: 'IMAGE_UPLOAD_FAILED',
    INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  },
  SERVER: {
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
  }
};

module.exports = ERROR_CODES;
